train_data_path: ./data/all_data.parquet

ab_cat_feats:
  - inning
  - inning_topbot
  - pitcher_name
  - batter_name
  
ab_num_feats: []

pitch_cat_feats:
  - pitch_name
  - description
  - events

pitch_num_feats:
  - release_speed

n_buckets: 32

n_workers: 0
# Multiply by accumulate_batches to get actual rate.
log_every_n: 5

# Network spec
precision: bf16-mixed
model_params:
  d_model: 192
  ff_dim: 576
  n_layers: 4
  n_heads: 4
  position_encoding: rope
  pe_args:
    theta: 10000.0
    # You have to set this later.
    max_seq_len: null

# Learning dynamics
max_epochs: 16
learning_rate: 0.005
batch_size: 32
accumulate_batches: 16

# lol as if
checkpoint_path: null
