train_data_path: ./data/all_data.parquet

ab_cat_feats:
  - inning
  - inning_topbot
  - pitcher_name
  - batter_name
  
ab_num_feats: []

pitch_cat_feats:
  - pitch_name
  - description
  - events

pitch_num_feats:
  - release_speed

n_buckets: 32

n_workers: 0
# Multiply by accumulate_batches to get actual rate.
log_every_n: 5

# Network spec
precision: bf16-mixed
model_params:
  d_model: 256
  ff_dim: 768
  n_layers: 4
  n_heads: 4

# Learning dynamics
max_epochs: 12
learning_rate: 0.02
batch_size: 32
accumulate_batches: 16

# lol as if
checkpoint_path: null
